dist: trusty
sudo: required
language: node_js
services:
  - docker
install:
  - docker build -t osboo/masonsmafia-db -f masonsmafia/Dockerfile.db ./masonsmafia/.
  - docker build -t osboo/masonsmafia-app ./masonsmafia/.
  - docker-compose -f docker-compose.test.yml up -d
  - docker exec -it -e MASONS_ENV=TEST testdb coffee src/server/init.coffee

script:
  - docker exec -it testapp npm run test