FROM mysql:latest

# Prepare sync script that can be triggered outside

# Install npm and coffee
RUN apt-get update && apt-get -y install curl
RUN curl -sL https://deb.nodesource.com/setup_9.x | bash -
RUN apt-get remove gyp
RUN apt-get -y install nodejs build-essential npm

# Install sequalize
COPY ./db/package*.json ./

RUN npm install

# Bundle app source
COPY ./src/server/conf.js ./src/server/conf.js
COPY ./src/server/init.js ./src/server/init.js
COPY ./src/server/models/. ./src/server/models/.

# Expose port
EXPOSE 3306