// Generated by CoffeeScript 2.2.3
(function() {
    let computerPersonal;

    computerPersonal = require('../models/ComputePersonal');

    module.exports = function(app) {
      app.get('/', function(req, res) {
        let context, viewName;
        viewName = 'common_statistics';
        context = {};
        return res.render(viewName, context);
      });
      app.get('/personal', function(req, res) {
        let context, viewName;
        viewName = 'personal_statistics';
        context = {};
        return res.render(viewName, context);
      });
      app.get('/personal/:name', function(req, res) {
        let context, viewName;
        viewName = 'personal_statistics';
        context = {
          'name': req.params.name,
        };
        return res.render(viewName, context);
      });
      app.get('/personal_stat', async function(req, res) {
        let error, profile;
        try {
          profile = (await computerPersonal(req.query.name));
          return res.json(profile);
        } catch (error1) {
          error = error1;
          return res.status(404).send(JSON.stringify(error));
        }
      });
      return app.get('/help', function(req, res) {
        return res.render('help', {});
      });
    };
  }).call(this); // eslint-disable-line no-invalid-this
