import 'bootstrap/dist/css/bootstrap.min.css'
import 'font-awesome/css/font-awesome.css'
import 'morris.js/morris.css'

import 'jquery-ui/ui/widgets/tooltip.js'
import 'tablesorter'
import 'bootstrap/dist/js/bootstrap.min.js'
import 'moment'
import 'moment/lang/ru'
import 'morris.js/morris.min.js'
import 'raphael'
import 'typeahead.js/dist/bloodhound.min.js'
import 'typeahead.js'